### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by vidzo** [bkleiner/redsky#1]
![protection](https://user-images.githubusercontent.com/24621278/113493471-63e89b00-94d7-11eb-86de-b8362f636bb6.png)
![option](https://user-images.githubusercontent.com/24621278/113493472-64813180-94d7-11eb-949a-66bf8bda6d28.png)
![connect2](https://user-images.githubusercontent.com/24621278/113493473-6519c800-94d7-11eb-95ef-1bba24d158de.png)
![connect](https://user-images.githubusercontent.com/24621278/113493474-6519c800-94d7-11eb-82b3-21d9df897271.png)
![upload](https://user-images.githubusercontent.com/24621278/113493213-592d0680-94d5-11eb-9ab7-fb9d6bcac14a.png)
![build](https://user-images.githubusercontent.com/24621278/113493214-59c59d00-94d5-11eb-94b6-eddc2c0e88f3.png)
![Folder](https://user-images.githubusercontent.com/24621278/113493215-59c59d00-94d5-11eb-919d-b7f0460afc93.png)
![Platform](https://user-images.githubusercontent.com/24621278/113493216-5a5e3380-94d5-11eb-9158-14c44b6a2265.png)

**Comment by bkleiner** [comment]
images are up, closing
